<?php
use MMIG46\Core\I18n;use MMIG46\Core\Security;
$draft=!$invoice||($invoice['status']??'draft')==='draft';
$displayItems=$items?:[['description'=>'','quantity_millis'=>1000,'unit'=>'Stück','unit_net_cents'=>0,'tax_rate_basis_points'=>1900]];
$money=static fn($c)=>number_format(((int)$c)/100,2,',','.').' €';
?>
<section class="page admin-shell"><div class="admin-hero"><div><p class="eyebrow">Verwaltung</p><h1>Rechnungen</h1><p>Entwürfe erstellen, prüfen, finalisieren und sicher versenden.</p></div><div class="admin-hero-actions"><a class="button ghost" href="<?= Security::e(I18n::url('/verwaltung')) ?>">Zur Verwaltung</a><a class="button ghost" href="<?= Security::e(I18n::url('/verwaltung/rechnungen')) ?>">Neue Rechnung</a></div></div>

<section class="admin-card admin-card-wide"><h2>Aussteller- und Zahlungseinstellungen</h2><p>Fehlende Pflichtangaben blockieren die Finalisierung.</p><?php $requiredSettings=['invoice_number_prefix'=>'Rechnungsnummer-Präfix','invoice_issuer_name'=>'Ausstellername','invoice_issuer_street'=>'Straße','invoice_issuer_postal_code'=>'PLZ','invoice_issuer_city'=>'Ort','invoice_issuer_country'=>'Land','invoice_tax_number_or_vat_id'=>'Steuernummer oder USt-ID','invoice_iban'=>'IBAN'];$missingSettings=array_filter($requiredSettings,static fn($label,$key)=>trim((string)($settings[$key]??''))==='',ARRAY_FILTER_USE_BOTH);if($missingSettings): ?><p class="notice"><strong>Finalisierung gesperrt:</strong> Es fehlen <?= Security::e(implode(', ',$missingSettings)) ?>.</p><?php else: ?><p>Alle für die Finalisierung vorausgesetzten Angaben sind vorhanden.</p><?php endif; ?><details><summary>Einstellungen bearbeiten</summary><form method="post" action="<?= Security::e(I18n::url('/verwaltung/rechnungen/einstellungen')) ?>" class="admin-form"><?= Security::csrfField() ?>
<?php foreach(['invoice_number_prefix'=>'Nummernpräfix','invoice_issuer_name'=>'Ausstellername','invoice_issuer_street'=>'Straße','invoice_issuer_postal_code'=>'PLZ','invoice_issuer_city'=>'Ort','invoice_issuer_country'=>'Land','invoice_tax_number_or_vat_id'=>'Steuernummer oder USt-ID','invoice_iban'=>'IBAN','invoice_bic'=>'BIC','invoice_bank_name'=>'Bank','invoice_footer_note_de'=>'Fußzeile Deutsch','invoice_footer_note_en'=>'Footer English'] as $key=>$label): ?><label><?= Security::e($label) ?><input name="<?= Security::e($key) ?>" value="<?= Security::e($settings[$key]??'') ?>" maxlength="500"></label><?php endforeach; ?><button class="primary" type="submit">Einstellungen speichern</button></form></details></section>

<section class="admin-card admin-card-wide"><h2><?= $invoice?'Rechnung #'.(int)$invoice['id']:'Neuer Rechnungsentwurf' ?></h2>
<?php if($draft): ?>
<form method="post" action="<?= Security::e(I18n::url('/verwaltung/rechnungen/speichern')) ?>" class="admin-form" id="invoice-form"><?= Security::csrfField() ?><input type="hidden" name="invoice_id" value="<?= (int)($invoice['id']??0) ?>"><input type="hidden" name="member_id" id="member-id" value="<?= (int)($invoice['member_id']??0) ?>"><input type="hidden" name="user_id" id="user-id" value="<?= (int)($invoice['user_id']??0) ?>">
<label>Daten aus Mitglied/Benutzer übernehmen<select id="recipient-source"><option value="">Bitte wählen</option><?php foreach($members as $m): $payload=['type'=>'member','id'=>(int)$m['id'],'name'=>$m['invoice_name']?:$m['name'],'email'=>$m['email'],'street'=>$m['street'],'postal_code'=>$m['postal_code'],'city'=>$m['city'],'country'=>$m['country']]; ?><option data-recipient="<?= Security::e(json_encode($payload,JSON_HEX_APOS|JSON_HEX_QUOT)) ?>">Mitglied: <?= Security::e($m['name']) ?></option><?php endforeach; ?><?php foreach($users as $u): $payload=['type'=>'user','id'=>(int)$u['id'],'name'=>$u['name'],'email'=>$u['email'],'street'=>'','postal_code'=>'','city'=>'','country'=>'Deutschland']; ?><option data-recipient="<?= Security::e(json_encode($payload,JSON_HEX_APOS|JSON_HEX_QUOT)) ?>">Benutzer: <?= Security::e($u['name']) ?></option><?php endforeach; ?></select></label><button type="button" id="copy-recipient">Auswahl übernehmen</button>
<div class="admin-grid"><label>Rechnungsempfänger<input id="recipient-name" name="recipient_name" required maxlength="255" value="<?= Security::e($invoice['recipient_name']??'') ?>"></label><label>E-Mail<input id="recipient-email" type="email" name="recipient_email" required maxlength="190" value="<?= Security::e($invoice['recipient_email']??'') ?>"></label><label>Straße<input id="recipient-street" name="recipient_street" required maxlength="255" value="<?= Security::e($invoice['recipient_street']??'') ?>"></label><label>PLZ<input id="recipient-postal-code" name="recipient_postal_code" required maxlength="20" value="<?= Security::e($invoice['recipient_postal_code']??'') ?>"></label><label>Ort<input id="recipient-city" name="recipient_city" required maxlength="150" value="<?= Security::e($invoice['recipient_city']??'') ?>"></label><label>Land<input id="recipient-country" name="recipient_country" required maxlength="100" value="<?= Security::e($invoice['recipient_country']??'Deutschland') ?>"></label></div>
<div class="admin-grid"><label>Sprache<select name="language"><option value="de" <?= ($invoice['language']??'de')==='de'?'selected':'' ?>>Deutsch</option><option value="en" <?= ($invoice['language']??'de')==='en'?'selected':'' ?>>English</option></select></label><label>Rechnungsanlass<input name="occasion" required maxlength="255" value="<?= Security::e($invoice['occasion']??'') ?>"></label><label>Leistung von<input type="date" name="service_start" required value="<?= Security::e($invoice['service_start']??date('Y-m-d')) ?>"></label><label>Leistung bis<input type="date" name="service_end" required value="<?= Security::e($invoice['service_end']??date('Y-m-d')) ?>"></label><label>Rechnungsdatum<input type="date" name="invoice_date" required value="<?= Security::e($invoice['invoice_date']??date('Y-m-d')) ?>"></label><label>Zahlungsziel<input type="date" name="due_date" required value="<?= Security::e($invoice['due_date']??date('Y-m-d',strtotime('+14 days'))) ?>"></label></div>
<h3>Positionen</h3><div class="table"><table id="items"><thead><tr><th>Bezeichnung</th><th>Menge</th><th>Einheit</th><th>Einzelpreis netto</th><th>USt. %</th><th></th></tr></thead><tbody><?php foreach($displayItems as $item): ?><tr><td><input name="items[description][]" required maxlength="500" value="<?= Security::e($item['description']??'') ?>"></td><td><input name="items[quantity][]" inputmode="decimal" required value="<?= Security::e(number_format(((int)($item['quantity_millis']??1000))/1000,3,',','')) ?>"></td><td><input name="items[unit][]" required maxlength="40" value="<?= Security::e($item['unit']??'Stück') ?>"></td><td><input name="items[unit_price][]" inputmode="decimal" required value="<?= Security::e(number_format(((int)($item['unit_net_cents']??0))/100,2,',','')) ?>"></td><td><input name="items[tax_rate][]" inputmode="decimal" required value="<?= Security::e(number_format(((int)($item['tax_rate_basis_points']??1900))/100,2,',','')) ?>"></td><td><button type="button" class="remove-item">×</button></td></tr><?php endforeach; ?></tbody></table></div><button type="button" id="add-item">Position hinzufügen</button><p id="client-total">Die verbindliche Berechnung erfolgt serverseitig.</p><label>Hinweise<textarea name="notes" rows="3"><?= Security::e($invoice['notes']??'') ?></textarea></label><button class="primary" type="submit">Entwurf speichern</button></form>
<?php if($invoice): ?><div class="admin-hero-actions"><a class="button ghost" target="_blank" href="<?= Security::e(I18n::url('/verwaltung/rechnungen/'.(int)$invoice['id'].'/vorschau')) ?>">PDF-Vorschau</a></div><form method="post" action="<?= Security::e(I18n::url('/verwaltung/rechnungen/'.(int)$invoice['id'].'/finalisieren')) ?>" class="admin-form"><?= Security::csrfField() ?><label>Zur endgültigen Finalisierung FINALISIEREN eingeben<input name="confirmation" required></label><button class="primary">Finalisieren</button></form><form method="post" action="<?= Security::e(I18n::url('/verwaltung/rechnungen/'.(int)$invoice['id'].'/loeschen')) ?>" class="admin-form"><?= Security::csrfField() ?><label>Zum Löschen ENTWURF LÖSCHEN eingeben<input name="confirmation" required></label><button>Entwurf löschen</button></form><?php endif; ?>
<?php else: ?><p><strong><?= Security::e($invoice['invoice_number']) ?></strong> · Status: <?= Security::e($invoice['status']) ?> · Brutto: <?= $money($invoice['gross_cents']) ?></p><p>Empfänger: <?= Security::e($invoice['recipient_name']) ?>, <?= Security::e($invoice['recipient_email']) ?></p><a class="button ghost" target="_blank" href="<?= Security::e(I18n::url('/verwaltung/rechnungen/'.(int)$invoice['id'].'/pdf')) ?>"><?= $invoice['status']==='cancelled'?'Storno-PDF anzeigen':'Finale PDF anzeigen' ?></a><?php if($invoice['status']==='cancelled'): ?> <a class="button ghost" target="_blank" href="<?= Security::e(I18n::url('/verwaltung/rechnungen/'.(int)$invoice['id'].'/original-pdf')) ?>">Unveränderte Originalrechnung</a><?php endif; ?>
<?php if(in_array($invoice['status'],['finalized','sent','paid'],true)): ?><form method="post" action="<?= Security::e(I18n::url('/verwaltung/rechnungen/'.(int)$invoice['id'].'/versenden')) ?>" class="admin-form"><?= Security::csrfField() ?><label>Empfängeradresse zur Bestätigung exakt eingeben: <?= Security::e($invoice['recipient_email']) ?><input type="email" name="recipient_confirmation" required></label><button class="primary">PDF per E-Mail versenden</button></form><?php endif; ?>
<?php if(in_array($invoice['status'],['finalized','sent'],true)): ?><form method="post" action="<?= Security::e(I18n::url('/verwaltung/rechnungen/'.(int)$invoice['id'].'/bezahlt')) ?>" class="admin-form"><?= Security::csrfField() ?><label>BEZAHLT eingeben<input name="confirmation" required></label><button>Zahlung dokumentieren</button></form><?php endif; ?>
<?php if($invoice['status']!=='cancelled'): ?><form method="post" action="<?= Security::e(I18n::url('/verwaltung/rechnungen/'.(int)$invoice['id'].'/stornieren')) ?>" class="admin-form"><?= Security::csrfField() ?><label>Stornierungsgrund<textarea name="reason" required maxlength="500"></textarea></label><label>STORNIEREN eingeben<input name="confirmation" required></label><button>Rechnung stornieren</button></form><?php endif; ?>
<?php foreach($outbox as $mail): ?><p>Versand an <?= Security::e($mail['recipient']) ?>: <strong><?= Security::e($mail['status']) ?></strong>, <?= (int)$mail['attempts'] ?> Versuch(e)<?= $mail['sent_at']?' · versendet '.Security::e($mail['sent_at']):'' ?><?= $mail['last_error']?' · letzter Fehler: '.Security::e($mail['last_error']):'' ?><?php if($mail['status']!=='sent'&&$invoice['status']!=='cancelled'): ?><form class="inline" method="post" action="<?= Security::e(I18n::url('/verwaltung/rechnungen/outbox/'.(int)$mail['id'].'/retry')) ?>"><?= Security::csrfField() ?><input type="hidden" name="invoice_id" value="<?= (int)$invoice['id'] ?>"><button>Erneut senden</button></form><?php endif; ?></p><?php endforeach; ?>
<?php endif; ?></section>

<section class="admin-card admin-card-wide"><h2>Bestehende Rechnungen</h2><div class="table"><table><thead><tr><th>Nummer</th><th>Empfänger</th><th>Datum</th><th>Status</th><th>Brutto</th></tr></thead><tbody><?php foreach($invoices as $row): ?><tr><td><a href="<?= Security::e(I18n::url('/verwaltung/rechnungen/'.(int)$row['id'])) ?>"><?= Security::e($row['invoice_number']?:'Entwurf #'.$row['id']) ?></a></td><td><?= Security::e($row['recipient_name']) ?></td><td><?= Security::e($row['invoice_date']) ?></td><td><?= Security::e($row['status']) ?></td><td><?= $money($row['gross_cents']) ?></td></tr><?php endforeach; ?></tbody></table></div></section></section>
<script>
(()=>{const table=document.querySelector('#items tbody');if(!table)return;document.querySelector('#add-item').addEventListener('click',()=>{const r=table.rows[0].cloneNode(true);r.querySelectorAll('input').forEach(i=>{i.value=i.name.includes('quantity')?'1,000':i.name.includes('unit_price')?'0,00':i.name.includes('tax_rate')?'19,00':i.name.includes('unit')?'Stück':''});table.append(r)});table.addEventListener('click',e=>{if(e.target.classList.contains('remove-item')&&table.rows.length>1)e.target.closest('tr').remove()});document.querySelector('#copy-recipient')?.addEventListener('click',()=>{const o=document.querySelector('#recipient-source').selectedOptions[0];if(!o?.dataset.recipient)return;const d=JSON.parse(o.dataset.recipient);for(const k of ['name','email','street','postal_code','city','country'])document.querySelector('#recipient-'+k.replace('_','-')).value=d[k]||'';document.querySelector('#member-id').value=d.type==='member'?d.id:0;document.querySelector('#user-id').value=d.type==='user'?d.id:0});})();
</script>
