-- EINMALIGE Migration. Voraussetzung: 2026_membership_workflow_admin.sql wurde ausgeführt.
-- Vorher vollständiges Datenbank- und Dateibackup erstellen.

CREATE TABLE invoice_number_sequences (
  sequence_year SMALLINT UNSIGNED PRIMARY KEY,
  next_number INT UNSIGNED NOT NULL DEFAULT 1,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE invoices (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  member_id INT UNSIGNED NULL,
  user_id INT UNSIGNED NULL,
  status ENUM('draft','finalized','sent','paid','cancelled') NOT NULL DEFAULT 'draft',
  language ENUM('de','en') NOT NULL DEFAULT 'de',
  invoice_number VARCHAR(40) NULL,
  sequence_year SMALLINT UNSIGNED NULL,
  sequence_number INT UNSIGNED NULL,
  recipient_name VARCHAR(255) NOT NULL,
  recipient_email VARCHAR(190) NOT NULL,
  recipient_street VARCHAR(255) NOT NULL,
  recipient_postal_code VARCHAR(20) NOT NULL,
  recipient_city VARCHAR(150) NOT NULL,
  recipient_country VARCHAR(100) NOT NULL,
  occasion VARCHAR(255) NOT NULL,
  service_start DATE NOT NULL,
  service_end DATE NOT NULL,
  invoice_date DATE NOT NULL,
  due_date DATE NOT NULL,
  notes TEXT NULL,
  net_cents BIGINT NOT NULL DEFAULT 0,
  tax_cents BIGINT NOT NULL DEFAULT 0,
  gross_cents BIGINT NOT NULL DEFAULT 0,
  issuer_snapshot_json LONGTEXT NULL,
  finalized_snapshot_json LONGTEXT NULL,
  pdf_storage_key CHAR(64) NULL,
  pdf_sha256 CHAR(64) NULL,
  cancellation_pdf_storage_key CHAR(64) NULL,
  cancellation_pdf_sha256 CHAR(64) NULL,
  created_by INT UNSIGNED NOT NULL,
  updated_by INT UNSIGNED NOT NULL,
  finalized_by INT UNSIGNED NULL,
  sent_by INT UNSIGNED NULL,
  paid_by INT UNSIGNED NULL,
  cancelled_by INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  finalized_at DATETIME NULL,
  sent_at DATETIME NULL,
  paid_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  cancellation_reason VARCHAR(500) NULL,
  UNIQUE KEY uq_invoices_number (invoice_number),
  UNIQUE KEY uq_invoices_sequence (sequence_year, sequence_number),
  INDEX idx_invoices_status_date (status, invoice_date),
  INDEX idx_invoices_member (member_id),
  INDEX idx_invoices_user (user_id),
  CONSTRAINT fk_invoices_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL,
  CONSTRAINT fk_invoices_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_invoices_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_finalized_by FOREIGN KEY (finalized_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_sent_by FOREIGN KEY (sent_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_paid_by FOREIGN KEY (paid_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE invoice_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  invoice_id INT UNSIGNED NOT NULL,
  position_no SMALLINT UNSIGNED NOT NULL,
  description VARCHAR(500) NOT NULL,
  quantity_millis BIGINT UNSIGNED NOT NULL,
  unit VARCHAR(40) NOT NULL,
  unit_net_cents BIGINT NOT NULL,
  tax_rate_basis_points INT UNSIGNED NOT NULL,
  line_net_cents BIGINT NOT NULL,
  line_tax_cents BIGINT NOT NULL,
  line_gross_cents BIGINT NOT NULL,
  UNIQUE KEY uq_invoice_item_position (invoice_id, position_no),
  CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO site_settings (setting_key, setting_value) VALUES
  ('invoice_number_prefix', 'MMIG46'),
  ('invoice_issuer_name', ''),
  ('invoice_issuer_street', ''),
  ('invoice_issuer_postal_code', ''),
  ('invoice_issuer_city', ''),
  ('invoice_issuer_country', 'Deutschland'),
  ('invoice_tax_number_or_vat_id', ''),
  ('invoice_iban', ''),
  ('invoice_bic', ''),
  ('invoice_bank_name', ''),
  ('invoice_footer_note_de', ''),
  ('invoice_footer_note_en', '');
